import React, { useState } from 'react';
import { 
  Phone, 
  Mail, 
  MapPin, 
  Send, 
  MessageSquare, 
  CheckCircle, 
  Sparkles, 
  Clock, 
  Building, 
  ArrowRight,
  ShieldCheck,
  AlertCircle
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { BRAND_INFO } from '../data/sodaData';

export default function ContactEnquiry({ onSaveLead }) {
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    city: '',
    state: '',
    tier: 'Tier 3 Cities',
    investmentCapacity: '₹12L - ₹15L',
    notes: '',
  });

  const [submitted, setSubmitted] = useState(false);
  const [lastSubmittedLead, setLastSubmittedLead] = useState(null);
  const [errorMsg, setErrorMsg] = useState('');

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    if (errorMsg) setErrorMsg('');
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!formData.name.trim() || !formData.phone.trim() || !formData.email.trim() || !formData.city.trim() || !formData.state.trim() || !formData.notes.trim()) {
      setErrorMsg('Please complete all required fields marked with * (Name, Phone, Email, City, State, and Message).');
      return;
    }

    const newLead = {
      id: `LEAD-${Date.now().toString().slice(-4)}`,
      ...formData,
      status: 'New',
      date: new Date().toISOString().split('T')[0],
    };

    // Save to App State / Local Storage
    onSaveLead(newLead);
    setLastSubmittedLead(newLead);
    setSubmitted(true);

    // Confetti Celebration
    confetti({
      particleCount: 80,
      spread: 70,
      origin: { y: 0.6 },
      colors: ['#d90429', '#ffb703', '#2b9348', '#00b4d8'],
    });

    // Create configured mailto link to company email
    const emailSubject = encodeURIComponent(`New Franchise Enquiry: ${formData.name} - ${formData.city}`);
    const emailBody = encodeURIComponent(
      `Hello Himmat Beverages Management,\n\nA new franchise enquiry has been submitted via the Daddy Soda House brand website:\n\n` +
      `Name: ${formData.name}\n` +
      `Phone: ${formData.phone}\n` +
      `Email: ${formData.email || 'Not provided'}\n` +
      `Target City / Location: ${formData.city}\n` +
      `Franchise Category: ${formData.tier}\n` +
      `Investment Readiness: ${formData.investmentCapacity}\n` +
      `Notes / Commercial Space: ${formData.notes || 'None'}\n\n` +
      `Generated by S Daddy Soda House Website Portal.`
    );
    
    // Suggest opening default mail client to dispatch
    const mailtoUrl = `mailto:${BRAND_INFO.email}?subject=${emailSubject}&body=${emailBody}`;
    
    // Keep reference for direct trigger
    window._latestMailto = mailtoUrl;
  };

  const handleSendEmailDirect = () => {
    if (window._latestMailto) {
      window.location.href = window._latestMailto;
    }
  };

  const handleSendWhatsAppDirect = () => {
    if (!lastSubmittedLead) return;
    const text = encodeURIComponent(
      `Hello Daddy Soda House team! I just submitted a franchise enquiry on your website.\n\n*Name:* ${lastSubmittedLead.name}\n*City:* ${lastSubmittedLead.city}\n*Phone:* ${lastSubmittedLead.phone}\n*Tier:* ${lastSubmittedLead.tier}\n*Investment:* ${lastSubmittedLead.investmentCapacity}\n\nPlease share the franchise prospectus and next steps.`
    );
    window.open(`https://wa.me/${BRAND_INFO.whatsappNumber}?text=${text}`, '_blank');
  };

  const resetForm = () => {
    setFormData({
      name: '',
      phone: '',
      email: '',
      city: '',
      tier: 'Tier 3 Cities',
      investmentCapacity: '₹12L - ₹15L',
      notes: '',
    });
    setSubmitted(false);
  };

  return (
    <section 
      id="contact"
      className="contact-section"
      style={{
        padding: '90px 0',
        backgroundColor: '#ffffff',
        borderTop: '1px solid #ede4d5',
        position: 'relative',
      }}
    >
      <div className="site-container">
        {/* Section Header */}
        <div style={{ textAlign: 'center', maxWidth: '780px', margin: '0 auto 48px auto' }}>
          <div 
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px',
              backgroundColor: '#ffe3e3',
              color: '#d90429',
              padding: '6px 16px',
              borderRadius: '999px',
              fontSize: '0.8rem',
              fontWeight: 800,
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              marginBottom: '14px',
            }}
          >
            <Sparkles size={16} /> Fast-Track Franchise Application
          </div>

          <h2 style={{ fontSize: 'clamp(2rem, 3.5vw, 2.8rem)', color: '#271407', marginBottom: '16px' }}>
            Get In Touch & Express Your Interest
          </h2>

          <p style={{ fontSize: '1.05rem', color: '#6b5c52', lineHeight: 1.7 }}>
            Secure your preferred city and territory rights. All submissions are directly captured in our 
            management dashboard and routed to the executive director’s email.
          </p>
        </div>

        <div 
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: '40px',
            alignItems: 'start',
          }}
        >
          {/* Left Column: Direct Contact Details & Brand Credibility */}
          <div>
            <div 
              className="wood-card-dark"
              style={{
                padding: '36px',
                marginBottom: '24px',
                position: 'relative',
                overflow: 'hidden',
              }}
            >
              <div 
                style={{
                  position: 'absolute',
                  top: '-20px',
                  right: '-20px',
                  width: '120px',
                  height: '120px',
                  background: 'radial-gradient(circle, rgba(212,152,91,0.2), transparent)',
                  borderRadius: '50%',
                }}
              />

              <span style={{ fontSize: '0.78rem', color: '#ffb703', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                Himmat Beverages Head Office
              </span>
              <h3 style={{ fontSize: '1.6rem', color: '#ffffff', margin: '6px 0 16px 0' }}>
                S Daddy Soda House HQ
              </h3>
              <p style={{ color: '#e8c49a', fontSize: '0.9rem', lineHeight: 1.6, marginBottom: '24px' }}>
                A Venture of <strong>Himmat Group of Business (Est. 1973)</strong>. 
                Dedicated commercial manufacturing, syrup supply chain, and franchisee support center.
              </p>

              {/* Direct Touchpoints */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', marginBottom: '20px' }}>
                {/* Address */}
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'flex-start',
                    gap: '14px',
                    color: '#ffffff',
                    backgroundColor: 'rgba(255,255,255,0.08)',
                    padding: '12px 16px',
                    borderRadius: '12px',
                    border: '1px solid rgba(212,152,91,0.3)',
                  }}
                >
                  <div style={{ backgroundColor: '#b87b43', padding: '8px', borderRadius: '8px', marginTop: '2px' }}>
                    <MapPin size={18} color="#fff" />
                  </div>
                  <div>
                    <span style={{ fontSize: '0.72rem', color: '#e8c49a', textTransform: 'uppercase', fontWeight: 800 }}>Corporate Address</span>
                    <p style={{ margin: 0, fontWeight: 700, fontSize: '0.94rem', color: '#ffffff' }}>Himmat Beverages Pvt. Ltd.</p>
                    <p style={{ margin: 0, fontSize: '0.82rem', color: '#e8c49a' }}>Maharashtra, India</p>
                  </div>
                </div>

                {/* Phone */}
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '14px',
                    color: '#ffffff',
                    backgroundColor: 'rgba(255,255,255,0.08)',
                    padding: '12px 16px',
                    borderRadius: '12px',
                    border: '1px solid rgba(212,152,91,0.3)',
                  }}
                >
                  <div style={{ backgroundColor: '#2b9348', padding: '8px', borderRadius: '8px' }}>
                    <Phone size={18} color="#fff" />
                  </div>
                  <div>
                    <span style={{ fontSize: '0.72rem', color: '#e8c49a', textTransform: 'uppercase', fontWeight: 800 }}>Phone / Franchise Desk</span>
                    <p style={{ margin: 0, fontWeight: 800, fontSize: '1.05rem' }}>{BRAND_INFO.phoneFormatted}</p>
                  </div>
                </div>

                {/* Email */}
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '14px',
                    color: '#ffffff',
                    backgroundColor: 'rgba(255,255,255,0.08)',
                    padding: '12px 16px',
                    borderRadius: '12px',
                    border: '1px solid rgba(212,152,91,0.3)',
                  }}
                >
                  <div style={{ backgroundColor: '#d90429', padding: '8px', borderRadius: '8px' }}>
                    <Mail size={18} color="#fff" />
                  </div>
                  <div>
                    <span style={{ fontSize: '0.72rem', color: '#e8c49a', textTransform: 'uppercase', fontWeight: 800 }}>Email Address</span>
                    <p style={{ margin: 0, fontWeight: 700, fontSize: '0.88rem', wordBreak: 'break-all' }}>{BRAND_INFO.email}</p>
                  </div>
                </div>

                {/* Business Hours */}
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '14px',
                    color: '#ffffff',
                    backgroundColor: 'rgba(255,255,255,0.08)',
                    padding: '12px 16px',
                    borderRadius: '12px',
                    border: '1px solid rgba(212,152,91,0.3)',
                  }}
                >
                  <div style={{ backgroundColor: '#5c3518', padding: '8px', borderRadius: '8px' }}>
                    <Clock size={18} color="#ffd000" />
                  </div>
                  <div>
                    <span style={{ fontSize: '0.72rem', color: '#e8c49a', textTransform: 'uppercase', fontWeight: 800 }}>Business Hours</span>
                    <p style={{ margin: 0, fontWeight: 700, fontSize: '0.88rem' }}>Mon – Sat: 9:00 AM – 8:00 PM IST</p>
                  </div>
                </div>
              </div>

              {/* Contact Action Buttons (Prompt #22) */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px', marginBottom: '22px' }}>
                <a
                  href={`tel:${BRAND_INFO.phone}`}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px',
                    padding: '10px 8px',
                    backgroundColor: '#ffffff',
                    color: '#271407',
                    borderRadius: '10px',
                    fontFamily: 'var(--font-heading)',
                    fontWeight: 800,
                    fontSize: '0.82rem',
                    textDecoration: 'none',
                    textAlign: 'center',
                    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
                    transition: 'all 0.2s ease',
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#ffd000')}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = '#ffffff')}
                >
                  <Phone size={14} color="#2b9348" /> Call
                </a>

                <a
                  href={`mailto:${BRAND_INFO.email}`}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px',
                    padding: '10px 8px',
                    backgroundColor: '#ffffff',
                    color: '#271407',
                    borderRadius: '10px',
                    fontFamily: 'var(--font-heading)',
                    fontWeight: 800,
                    fontSize: '0.82rem',
                    textDecoration: 'none',
                    textAlign: 'center',
                    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
                    transition: 'all 0.2s ease',
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#ffd000')}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = '#ffffff')}
                >
                  <Mail size={14} color="#d90429" /> Email
                </a>

                <a
                  href={`https://wa.me/${BRAND_INFO.whatsappNumber}?text=${encodeURIComponent(BRAND_INFO.whatsappMessage)}`}
                  target="_blank"
                  rel="noreferrer"
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px',
                    padding: '10px 8px',
                    backgroundColor: '#25D366',
                    color: '#ffffff',
                    borderRadius: '10px',
                    fontFamily: 'var(--font-heading)',
                    fontWeight: 800,
                    fontSize: '0.82rem',
                    textDecoration: 'none',
                    textAlign: 'center',
                    boxShadow: '0 2px 8px rgba(37,211,102,0.3)',
                    transition: 'all 0.2s ease',
                  }}
                >
                  <MessageSquare size={14} /> Chat
                </a>
              </div>
            </div>

            {/* Quick Assurance Box */}
            <div 
              style={{
                backgroundColor: '#fdfbf7',
                borderRadius: '16px',
                padding: '20px',
                border: '1px solid #ede4d5',
                display: 'flex',
                alignItems: 'center',
                gap: '14px',
              }}
            >
              <ShieldCheck size={32} color="#2b9348" style={{ flexShrink: 0 }} />
              <div>
                <p style={{ margin: 0, fontWeight: 700, fontSize: '0.88rem', color: '#271407' }}>
                  Territory Exclusivity Guarantee
                </p>
                <p style={{ margin: 0, fontSize: '0.78rem', color: '#6b5c52' }}>
                  We assign designated protected radius rights for every verified franchise agreement.
                </p>
              </div>
            </div>
          </div>

          {/* Right Column: Interactive Franchise Enquiry Form */}
          <div 
            className="wood-card"
            style={{
              padding: '36px',
              backgroundColor: '#ffffff',
              border: '2px solid #d4985b',
            }}
          >
            {submitted ? (
              <div style={{ textAlign: 'center', padding: '30px 10px' }}>
                <div 
                  style={{
                    width: '64px',
                    height: '64px',
                    borderRadius: '50%',
                    backgroundColor: '#e8f5e9',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    margin: '0 auto 20px auto',
                  }}
                >
                  <CheckCircle size={36} color="#2b9348" />
                </div>

                <span style={{ backgroundColor: '#2b9348', color: '#fff', fontSize: '0.75rem', fontWeight: 800, padding: '3px 12px', borderRadius: '999px' }}>
                  APPLICATION RECORDED #{lastSubmittedLead?.id}
                </span>

                <h3 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.65rem', color: '#271407', margin: '14px 0 10px 0', fontWeight: 900 }}>
                  Thank you! Your franchise enquiry has been received.
                </h3>

                <p style={{ color: '#5c3518', fontSize: '0.95rem', lineHeight: 1.6, marginBottom: '24px' }}>
                  Your franchise application for <strong>{lastSubmittedLead?.city}</strong> has been saved to the
                  company Admin Portal and queued for <strong>himmat.beverages1290@gmail.com</strong>.
                </p>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <button
                    onClick={handleSendWhatsAppDirect}
                    style={{
                      backgroundColor: '#25D366',
                      color: '#ffffff',
                      border: 'none',
                      borderRadius: '12px',
                      padding: '14px',
                      fontFamily: 'var(--font-heading)',
                      fontWeight: 800,
                      fontSize: '0.92rem',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '8px',
                      cursor: 'pointer',
                    }}
                  >
                    <MessageSquare size={18} />
                    Dispatch Enquiry via WhatsApp to {BRAND_INFO.phoneFormatted}
                  </button>

                  <button
                    onClick={handleSendEmailDirect}
                    style={{
                      backgroundColor: '#271407',
                      color: '#ffffff',
                      border: 'none',
                      borderRadius: '12px',
                      padding: '12px',
                      fontFamily: 'var(--font-heading)',
                      fontWeight: 700,
                      fontSize: '0.88rem',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '8px',
                      cursor: 'pointer',
                    }}
                  >
                    <Mail size={16} />
                    Open Email Draft to {BRAND_INFO.email}
                  </button>

                  <button
                    onClick={resetForm}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: '#7b4a22',
                      cursor: 'pointer',
                      fontSize: '0.82rem',
                      textDecoration: 'underline',
                      marginTop: '6px',
                    }}
                  >
                    Submit another application
                  </button>
                </div>
              </div>
            ) : (
              <form onSubmit={handleSubmit}>
                <div style={{ marginBottom: '22px' }}>
                  <h3 style={{ fontSize: '1.4rem', color: '#271407', margin: 0 }}>
                    Franchise Application Form
                  </h3>
                  <p style={{ margin: '4px 0 0 0', fontSize: '0.82rem', color: '#7b4a22' }}>
                    Fields marked with * are required. We respond within 24 business hours.
                  </p>
                </div>

                {errorMsg && (
                  <div 
                    style={{
                      backgroundColor: '#ffebee',
                      color: '#c62828',
                      padding: '10px 14px',
                      borderRadius: '8px',
                      fontSize: '0.82rem',
                      marginBottom: '18px',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '8px',
                    }}
                  >
                    <AlertCircle size={16} /> {errorMsg}
                  </div>
                )}

                {/* Name */}
                <div style={{ marginBottom: '16px' }}>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                    Full Name *
                  </label>
                  <input
                    type="text"
                    name="name"
                    required
                    placeholder="e.g. Ketan Kadam / Rajesh Sharma"
                    value={formData.name}
                    onChange={handleChange}
                    style={{
                      width: '100%',
                      padding: '12px 14px',
                      borderRadius: '10px',
                      border: '1px solid #ede4d5',
                      outline: 'none',
                      fontSize: '0.9rem',
                    }}
                  />
                </div>

                {/* Phone & Email Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '16px' }}>
                  <div>
                    <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                      Contact Phone *
                    </label>
                    <input
                      type="tel"
                      name="phone"
                      required
                      placeholder="e.g. 9822455120"
                      value={formData.phone}
                      onChange={handleChange}
                      style={{
                        width: '100%',
                        padding: '12px 14px',
                        borderRadius: '10px',
                        border: '1px solid #ede4d5',
                        outline: 'none',
                        fontSize: '0.9rem',
                      }}
                    />
                  </div>

                  <div>
                    <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                      Email Address
                    </label>
                    <input
                      type="email"
                      name="email"
                      placeholder="you@gmail.com"
                      value={formData.email}
                      onChange={handleChange}
                      style={{
                        width: '100%',
                        padding: '12px 14px',
                        borderRadius: '10px',
                        border: '1px solid #ede4d5',
                        outline: 'none',
                        fontSize: '0.9rem',
                      }}
                    />
                  </div>
                </div>

                {/* City & State Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '16px' }}>
                  <div>
                    <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                      City *
                    </label>
                    <input
                      type="text"
                      name="city"
                      required
                      placeholder="e.g. Pune, Mumbai, Kolhapur..."
                      value={formData.city}
                      onChange={handleChange}
                      style={{
                        width: '100%',
                        padding: '12px 14px',
                        borderRadius: '10px',
                        border: '1px solid #ede4d5',
                        outline: 'none',
                        fontSize: '0.9rem',
                      }}
                    />
                  </div>

                  <div>
                    <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                      State *
                    </label>
                    <input
                      type="text"
                      name="state"
                      required
                      placeholder="e.g. Maharashtra"
                      value={formData.state}
                      onChange={handleChange}
                      style={{
                        width: '100%',
                        padding: '12px 14px',
                        borderRadius: '10px',
                        border: '1px solid #ede4d5',
                        outline: 'none',
                        fontSize: '0.9rem',
                      }}
                    />
                  </div>
                </div>

                {/* Tier & Investment Budget */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '16px' }}>
                  <div>
                    <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                      Franchise Model Tier
                    </label>
                    <select
                      name="tier"
                      value={formData.tier}
                      onChange={handleChange}
                      style={{
                        width: '100%',
                        padding: '12px 14px',
                        borderRadius: '10px',
                        border: '1px solid #ede4d5',
                        outline: 'none',
                        fontSize: '0.85rem',
                        backgroundColor: '#ffffff',
                      }}
                    >
                      <option value="Tier 3 Cities">Tier 3 Cities & Towns</option>
                      <option value="Tier 1 & 2 Cities">Tier 1 & 2 Metros</option>
                      <option value="High-Street Kiosk">High-Street Kiosk / Mall</option>
                    </select>
                  </div>

                  <div>
                    <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                      Investment Budget
                    </label>
                    <select
                      name="investmentCapacity"
                      value={formData.investmentCapacity}
                      onChange={handleChange}
                      style={{
                        width: '100%',
                        padding: '12px 14px',
                        borderRadius: '10px',
                        border: '1px solid #ede4d5',
                        outline: 'none',
                        fontSize: '0.85rem',
                        backgroundColor: '#ffffff',
                      }}
                    >
                      <option value="₹12L - ₹15L">₹12 Lakhs – ₹15 Lakhs</option>
                      <option value="₹15L - ₹25L">₹15 Lakhs – ₹25 Lakhs</option>
                      <option value="₹25L+ Multi-Unit">₹25L+ (Multi-Unit Franchise)</option>
                    </select>
                  </div>
                </div>

                {/* Message * */}
                <div style={{ marginBottom: '22px' }}>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: 700, color: '#3b2210', marginBottom: '6px' }}>
                    Message *
                  </label>
                  <textarea
                    name="notes"
                    required
                    rows="3"
                    placeholder="Tell us about your background, shop location (if available), or any questions..."
                    value={formData.notes}
                    onChange={handleChange}
                    style={{
                      width: '100%',
                      padding: '12px 14px',
                      borderRadius: '10px',
                      border: '1px solid #ede4d5',
                      outline: 'none',
                      fontSize: '0.85rem',
                      fontFamily: 'var(--font-body)',
                    }}
                  />
                </div>

                {/* Submit Button */}
                <button
                  type="submit"
                  className="btn-accent-soda"
                  style={{
                    width: '100%',
                    justifyContent: 'center',
                    padding: '14px',
                    fontSize: '1rem',
                  }}
                >
                  <Send size={18} />
                  <span>Submit Enquiry</span>
                </button>

                <p style={{ margin: '12px 0 0 0', textAlign: 'center', fontSize: '0.72rem', color: '#9c8e84' }}>
                  Enquiries are stored in the Admin Dashboard and routed to himmat.beverages1290@gmail.com
                </p>
              </form>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
